Repository siriwatknp/mui-treasury, pull requests merged in 2019-12, with the labels that each got.

#237 update lerna.json
  lerna.json
Labels: PR: Internal 🏠

#238 chore: 🤖 test update website
  website/src/global.css
Labels: PR: Internal 🏠

#239 feat: 🎸 add test.styles
  packages/mui-styles/src/test/test.styles.js
Labels: PR: New Feature 🚀

#240 fix: 🐛 return as object
  packages/mui-styles/src/test/test.styles.js
Labels: PR: Breaking Change 💥

#242 chore: 🤖 update readme
  packages/mui-layout/README.md
Labels: PR: Docs 📝, bug

#246 #209 layout examples
  packages/mui-layout/src/components/CollapseBtn.js
  packages/mui-layout/src/components/Sidebar.js
  packages/mui-layout/src/core/layoutContext.js
  packages/mui-layout/src/core/windowContext.js
  packages/mui-layout/src/hooks/index.js
  packages/mui-layout/src/hooks/useEventListener.js
  packages/mui-layout/src/hooks/useHeightAdjustment.js
  packages/mui-layout/src/hooks/useMediaQuery.js
  packages/mui-layout/src/hooks/useScreen.js
  packages/mui-layout/src/hooks/useWindow.js
  packages/mui-layout/src/index.js
  packages/mui-layout/src/presets/index.js
  website/gatsby-config.js
  website/src/App.js
  website/src/components/layout/Browser.js
  website/src/components/layout/BrowserIFrame.js
  website/src/components/layout/IFrame.js
  website/src/constants/menus.js
  website/src/containers/FrontMatter.js
  website/src/containers/SourceFile.js
  website/src/containers/SourceFileDrawer.js
  website/src/docs/layout/presets/contentBased/ContentBasedLayout.js
  website/src/docs/layout/presets/contentBased/index.md
  website/src/docs/layout/presets/cozy/CozyLayout.js
  website/src/docs/layout/presets/cozy/index.md
  website/src/docs/layout/presets/default/DefaultLayout.js
  website/src/docs/layout/presets/default/index.md
  website/src/docs/layout/presets/fixed/FixedLayout.js
  website/src/docs/layout/presets/fixed/index.md
  website/src/docs/layout/presets/index.js
  website/src/docs/layout/presets/muiTreasury/MuiTreasuryLayout.js
  website/src/docs/layout/presets/muiTreasury/index.md
  website/src/docs/layout/presets/standard/StandardLayout.js
  website/src/docs/layout/presets/standard/index.md
  website/src/pages/layout/demo.js
  website/src/pages/layout/examples/starter.js
  website/src/pages/layout/presets/content-based.js
  website/src/pages/layout/presets/cozy.js
  website/src/pages/layout/presets/default.js
  website/src/pages/layout/presets/fixed.js
  website/src/pages/layout/presets/mui-treasury.js
  website/src/pages/layout/presets/standard.js
  website/src/utils/functions.js
Labels: PR: Docs :memo:, PR: New Feature :rocket:

#249 fix: 🐛 bug copier & bug frontmatter component
  website/src/components/atoms/Copier.js
  website/src/components/molecules/Html.js
  website/src/containers/Demo/DemoSourceDrawer.js
  website/src/containers/FrontMatter.js
  website/src/containers/SourceFileDrawer.js
  website/src/docs/layout/presets/muiTreasury/index.js
  website/src/pages/layout/presets/mui-treasury.js
Labels: PR: Bug Fix :bug:

#253 clean code using path pattern matcher
  package.json
  website/src/App.js
  website/src/__tests__/modules/Path.test.js
  website/src/components/atoms/Copier.js
  website/src/components/layout/PageFooter.js
  website/src/components/layout/PageHeader.js
  website/src/components/layout/PageLayout.js
  website/src/containers/Demo/DemoSourceDrawer.js
  website/src/docs/layout/presets/contentBased/index.js
  website/src/docs/layout/presets/cozy/index.js
  website/src/docs/layout/presets/default/index.js
  website/src/docs/layout/presets/fixed/index.js
  website/src/docs/layout/presets/standard/index.js
  website/src/modules/path/Path.js
  website/src/modules/path/index.js
  website/src/pages/layout/presets/content-based.js
  website/src/pages/layout/presets/cozy.js
  website/src/pages/layout/presets/default.js
  website/src/pages/layout/presets/fixed.js
  website/src/pages/layout/presets/standard.js
Labels: PR: Refactor :bulb:

#259 fix: 🐛 persistentBehavior & fix bug clipped
  packages/mui-layout/src/__tests__/headerUtils.test.js
  packages/mui-layout/src/__tests__/utils.test.js
  packages/mui-layout/src/components/Header.js
  packages/mui-layout/src/components/Sidebar.js
  packages/mui-layout/src/presets/contentBased.js
  packages/mui-layout/src/utils/LayoutUtils.js
  packages/mui-layout/src/utils/createSidebarLayer.js
  packages/mui-layout/src/utils/getDefaultScreenConfig.js
  packages/mui-layout/src/utils/headerUtils.js
  packages/mui-layout/src/utils/sidebarUtils.js
  website/src/__temporary__/GetCode.js
Labels: PR: Breaking Change :boom:

#261 feat: 🎸 add new pkg @mui-treasury/mockup
  packages/mui-mockup/package.json
  packages/mui-mockup/src/layout/ContentEx.js
  packages/mui-mockup/src/layout/ContentForm.js
  packages/mui-mockup/src/layout/FooterEx.js
  packages/mui-mockup/src/layout/HeaderEx.js
  packages/mui-mockup/src/layout/NavContentEx.js
  packages/mui-mockup/src/layout/NavHeaderEx.js
  packages/mui-mockup/src/layout/RouterNavEx.js
  packages/mui-mockup/src/layout/index.js
  website/gatsby-config.js
  website/src/docs/layout/basicExamples/controlSidebar/ControlSidebarDemo.js
  website/src/docs/layout/basicExamples/customStyles/CustomStylesDemo.js
  website/src/docs/layout/basicExamples/customTheme/CustomThemeDemo.js
  website/src/docs/layout/basicExamples/secondarySidebar/SecondarySidebarDemo.js
  website/src/docs/layout/presets/contentBased/ContentBasedLayout.js
  website/src/docs/layout/presets/cozy/CozyLayout.js
  website/src/docs/layout/presets/default/DefaultLayout.js
  website/src/docs/layout/presets/fixed/FixedLayout.js
  website/src/docs/layout/presets/muiTreasury/MuiTreasuryLayout.js
  website/src/docs/layout/presets/standard/StandardLayout.js
  webstorm-config.js
  yarn.lock
Labels: PR: New Feature :rocket:

#290 feat: 🎸 add InsetSidebar example
  packages/mui-layout/src/__tests__/configGenerator.test.js
  packages/mui-layout/src/__tests__/presets.test.js
  packages/mui-layout/src/components/Footer.js
  packages/mui-layout/src/components/internal/SharedInsetSidebar.js
  packages/mui-layout/src/components/internal/SharedSidebarTrigger.js
  packages/mui-layout/src/hooks/index.js
  packages/mui-layout/src/hooks/useInsetBreakpoint.js
  packages/mui-layout/src/hooks/useScreenComparison.js
  packages/mui-layout/src/presets/contentBased.js
  packages/mui-layout/src/presets/cozy.js
  packages/mui-layout/src/presets/default.js
  packages/mui-layout/src/presets/fixed.js
  packages/mui-layout/src/presets/muiTreasury.js
  packages/mui-layout/src/presets/standard.js
  packages/mui-layout/src/utils/ConfigGenerator/AddOnsGenerator.js
  packages/mui-layout/src/utils/ConfigGenerator/ConfigGenerator.js
  packages/mui-layout/src/utils/ConfigGenerator/HeaderGenerator.js
  packages/mui-layout/src/utils/ConfigGenerator/SidebarGenerator.js
  packages/mui-layout/src/utils/ScreenConfigGenerator/ScreenConfigGenerator.js
  packages/mui-layout/src/utils/ScreenConfigGenerator/index.js
  packages/mui-layout/src/utils/createSet.js
  packages/mui-layout/src/utils/index.js
  packages/mui-mockup/src/layout/ContentEx.js
  packages/mui-mockup/src/layout/HeaderEx.js
  website/src/constants/menus.js
  website/src/docs/layout/basicExamples/insetSidebar/InsetSidebarDemo.js
  website/src/docs/layout/basicExamples/insetSidebar/index.js
  website/src/docs/layout/basicExamples/insetSidebar/index.md
  website/src/pages/layout/basic-examples/inset-sidebar.js
Labels: PR: Docs :memo:, scope: website

#292 Fix bugs website
  website/src/App.js
  website/src/components/layout/Browser.js
  website/src/components/layout/PageHeader.js
  website/src/components/layout/PageLayout.js
  website/src/modules/path/Path.js
Labels: PR: Bug Fix :bug:

#294 docs: ✏️ add nextjs starter
  starters/nextjs/.gitignore
  starters/nextjs/README.md
  starters/nextjs/next.config.js
  starters/nextjs/package.json
  starters/nextjs/pages/index.js
  starters/nextjs/yarn.lock
Labels: PR: Docs :memo:

#296 Mockup darkmode & React clone
  packages/mui-layout/src/components/Content.js
  packages/mui-layout/src/components/internal/SharedInsetSidebar.js
  packages/mui-layout/src/utils/ConfigGenerator/ConfigGenerator.js
  packages/mui-mockup/src/brands/index.js
  packages/mui-mockup/src/brands/reactjs/ReactContent.js
  packages/mui-mockup/src/brands/reactjs/ReactHeader.js
  packages/mui-mockup/src/brands/reactjs/ReactNextArticle.js
  packages/mui-mockup/src/brands/reactjs/index.js
  packages/mui-mockup/src/components/index.js
  packages/mui-mockup/src/components/listItem/BlueListItem.js
  packages/mui-mockup/src/components/listItem/WhiteIconItem.js
  packages/mui-mockup/src/components/listItem/index.js
  packages/mui-mockup/src/components/logo/TextLogo.js
  packages/mui-mockup/src/components/logo/index.js
  packages/mui-mockup/src/layout/NavHeaderEx.js
  packages/mui-mockup/src/layout/index.js
  packages/mui-mockup/src/sidebars/RoundIconSidebar.js
  packages/mui-mockup/src/sidebars/TextSidebar.js
  packages/mui-mockup/src/sidebars/index.js
  packages/mui-utils/src/getThemeColor.js
  website/gatsby-browser.js
  website/gatsby-ssr.js
  website/src/components/layout/BrowserIFrame.js
  website/src/components/layout/PageLayout.js
  website/src/constants/menus.js
  website/src/contexts/router.js
  website/src/docs/layout/basicExamples/controlSidebar/ControlSidebarDemo.js
  website/src/docs/layout/basicExamples/customStyles/CustomStylesDemo.js
  website/src/docs/layout/basicExamples/customTheme/CustomThemeDemo.js
  website/src/docs/layout/basicExamples/insetSidebar/InsetSidebarDemo.js
  website/src/docs/layout/clones/reactjs/ReactJsDemo.js
  website/src/docs/layout/clones/reactjs/index.js
  website/src/docs/layout/clones/reactjs/index.md
  website/src/docs/layout/presets/contentBased/ContentBasedLayout.js
  website/src/docs/layout/presets/cozy/CozyLayout.js
  website/src/docs/layout/presets/default/DefaultLayout.js
  website/src/docs/layout/presets/fixed/FixedLayout.js
  website/src/docs/layout/presets/muiTreasury/MuiTreasuryLayout.js
  website/src/docs/layout/presets/standard/StandardLayout.js
  website/src/modules/path/Path.js
  website/src/pages/layout/clones/reactjs.js
  website/src/utils/useQueryParams.js
Labels: PR: style :lipstick:, scope: website

#315 docs: ✏️ add create-react-app starter
  starters/react-app/.gitignore
  starters/react-app/README.md
  starters/react-app/package.json
  starters/react-app/src/App.css
  starters/react-app/src/App.js
  starters/react-app/src/App.test.js
  starters/react-app/src/index.css
  starters/react-app/src/index.js
  starters/react-app/src/logo.svg
  starters/react-app/src/serviceWorker.js
  starters/react-app/src/setupTests.js
  starters/react-app/yarn.lock
Labels: PR: Docs :memo:

#326 fix: 🐛 old layout builder to use v3.1 code
  website/src/__temporary__/GetCode.js
Labels: PR: Bug Fix :bug:

#324 #213 add tag card style
  packages/mui-styles/src/cardContent/tag/index.js
  packages/mui-styles/src/cardContent/tag/tagCard.styles.js
  website/src/docs/components/card/tag/TagCard.js
  website/src/docs/components/card/tag/index.md
Labels: PR: New Feature :rocket:

#338 Layout percentage width
  packages/mui-layout/src/__tests__/models/insetSidebar.test.js
  packages/mui-layout/src/__tests__/models/width.test.js
  packages/mui-layout/src/models/insetSidebar.js
  packages/mui-layout/src/models/width.js
Labels: PR: New Feature :rocket:

#358 #303 fb messenger clone
  packages/mui-layout/src/__tests__/models/header.test.js
  packages/mui-layout/src/__tests__/models/insetSidebar.test.js
  packages/mui-layout/src/__tests__/models/width.test.js
  packages/mui-layout/src/adapters/sidebar.js
  packages/mui-layout/src/components/Footer.js
  packages/mui-layout/src/models/insetSidebar.js
  packages/mui-layout/src/models/width.js
  packages/mui-layout/src/styles/insetSidebar.styles.js
  packages/mui-layout/src/utils/ConfigGenerator/SidebarGenerator.js
  packages/mui-mockup/src/brands/messenger/ChatBar.js
  packages/mui-mockup/src/brands/messenger/ChatDialog.js
  packages/mui-mockup/src/brands/messenger/ChatList.js
  packages/mui-mockup/src/brands/messenger/ChatListItem.js
  packages/mui-mockup/src/brands/messenger/ChatMsg.js
  packages/mui-mockup/src/brands/messenger/ChatSettings.js
  packages/mui-mockup/src/brands/messenger/ChatsHeader.js
  packages/mui-mockup/src/brands/messenger/ConversationHead.js
  packages/mui-mockup/src/brands/messenger/MessengerSearch.js
  packages/mui-mockup/src/brands/messenger/index.js
  website/src/constants/menus.js
  website/src/docs/layout/clones/messenger/MessengerDemo.js
  website/src/docs/layout/clones/messenger/index.js
  website/src/docs/layout/clones/messenger/index.md
  website/src/pages/layout/clones/messenger.js
Labels: PR: Bug Fix :bug:, PR: New Feature :rocket:

#362 fix: 🐛 remove offline due to content missing & update manifest
  website/gatsby-config.js
  website/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#361 refs #257 copy read me
  scripts/copy-files.js
Labels: PR: Bug Fix :bug:
