Repository siriwatknp/mui-treasury, pull requests merged in 2020-04, with the labels that each got.

#621 feat: 🎸 #537 add BannerCheckboxStyle
  packages/mui-styles/src/checkbox/banner/bannerCheckbox.styles.js
  packages/mui-styles/src/checkbox/banner/index.js
  website/src/components/layout/PageLayout.js
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/checkbox/banner/BannerCheckboxStyle.js
  website/src/docs/styles/checkbox/banner/index.js
  website/src/docs/styles/checkbox/banner/index.md
  website/src/docs/styles/checkbox/index.js
  website/src/pages/styles/checkbox.js
Labels: PR: New Feature :rocket:

#625 🎸 #538 NeonCheckbox & NeonRadio style
  packages/mui-styles/src/checkbox/neon/index.js
  packages/mui-styles/src/checkbox/neon/neonCheckbox.styles.js
  packages/mui-styles/src/radio/neon/index.js
  packages/mui-styles/src/radio/neon/neonRadio.styles.js
  website/src/components/layout/PageLayout.js
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/checkbox/neon/NeonCheckboxStyle.js
  website/src/docs/styles/checkbox/neon/index.js
  website/src/docs/styles/checkbox/neon/index.md
  website/src/docs/styles/radio/index.js
  website/src/docs/styles/radio/neon/NeonRadioStyle.js
  website/src/docs/styles/radio/neon/index.js
  website/src/docs/styles/radio/neon/index.md
  website/src/pages/styles/radio.js
Labels: PR: New Feature :rocket:

#636 feat: 🎸 #546 add AirbnbSwitch style
  packages/mui-styles/src/switch/airbnb/airbnbSwitch.styles.js
  packages/mui-styles/src/switch/airbnb/index.js
  packages/mui-styles/src/switch/lovely/lovelySwitch.styles.js
  website/src/docs/styles/switch/airbnb/AirbnbSwitchStyle.js
  website/src/docs/styles/switch/airbnb/index.js
  website/src/docs/styles/switch/airbnb/index.md
Labels: PR: New Feature :rocket:

#638 #555 [Layout] change opened variable name
  packages/mui-layout/src/__tests__/context.test.js
  packages/mui-layout/src/__tests__/models/container.test.js
  packages/mui-layout/src/__tests__/models/content.test.js
  packages/mui-layout/src/__tests__/models/edgeEffect.test.js
  packages/mui-layout/src/__tests__/models/footer.test.js
  packages/mui-layout/src/__tests__/models/header.test.js
  packages/mui-layout/src/__tests__/secondarySidebar.test.js
  packages/mui-layout/src/__tests__/sidebar.test.js
  packages/mui-layout/src/adapters/sidebar.js
  packages/mui-layout/src/components/CollapseBtn.d.ts
  packages/mui-layout/src/components/SecondaryCollapseBtn.d.ts
  packages/mui-layout/src/components/internal/SharedCollapseBtn.d.ts
  packages/mui-layout/src/components/internal/SharedCollapseBtn.js
  packages/mui-layout/src/components/internal/SharedInsetSidebar.js
  packages/mui-layout/src/components/internal/SharedSidebar.js
  packages/mui-layout/src/components/internal/SharedSidebarTrigger.js
  packages/mui-layout/src/components/internal/SharedSidebarTriggerIcon.js
  packages/mui-layout/src/core/layoutContext.d.ts
  packages/mui-layout/src/core/layoutContext.js
  packages/mui-layout/src/models/edgeEffect.js
  website/src/__tests__/modules/Path.test.js
  website/src/pages/layout/index.js
Labels: PR: Refactor :bulb:

#649 [#624] fix: 🐛 add typescriptCopy to copy-files script
  packages/mui-layout/package.json
  scripts/copy-files.js
Labels: PR: Bug Fix :bug:

#652 [#650] fix: 🐛 ReactJs layout crash and bgcolor at content
  website/src/components/layout/PageLayout.js
  website/src/docs/layout/clones/reactjs/ReactJsDemo.js
Labels: PR: Bug Fix :bug:

#656 add missing HeaderOffset to types definition
  packages/mui-layout/src/components/index.d.ts
Labels: PR: Bug Fix :bug:
