Repository siriwatknp/mui-treasury, pull requests merged in 2020-05, with the labels that each got.

#719 #705 advanced layout docs
  packages/mui-layout/src/builders/EdgeSidebar/EdgeSidebarBuilder.ts
  packages/mui-layout/src/components/InsetContainer/InsetContainer.tsx
  website/gatsby-config.js
  website/package.json
  website/src/components/atoms/CodeSandbox.js
  website/src/constants/menus/layoutMenus.js
  website/src/global.css
  website/src/modules/path/Path.js
  website/src/pages/layout/advanced/controlling-sidebar.mdx
  website/src/pages/layout/advanced/dynamic-config.mdx
  website/src/pages/layout/advanced/hide-sidebar.mdx
  website/src/pages/layout/advanced/mutate-preset.mdx
  website/src/pages/layout/tutorials/blog-layout.mdx
  website/src/pages/layout/v3/builder.js
  website/src/templates/DocTemplate.js
  yarn.lock
Labels: PR: Docs :memo:

#726 #660 mui layout v4
  jest.config.js
  packages/mui-layout/src/__tests__/integration.spec.ts
  packages/mui-layout/src/builders/Content/ContentBuilder.ts
  packages/mui-layout/src/builders/EdgeSidebar/EdgeSidebarBuilder.spec.ts
  packages/mui-layout/src/builders/EdgeSidebar/EdgeSidebarBuilder.ts
  packages/mui-layout/src/builders/Footer/FooterBuilder.ts
  packages/mui-layout/src/builders/Header/HeaderBuilder.spec.ts
  packages/mui-layout/src/builders/Header/HeaderBuilder.ts
  packages/mui-layout/src/builders/InsetSidebar/InsetSidebarBuilder.ts
  packages/mui-layout/src/builders/LayoutBuilder.ts
  packages/mui-layout/src/types/Builder.ts
  website/src/App.js
  website/src/__tests__/modules/Path.test.js
  website/src/modules/path/Path.js
Labels: PR: New Feature :rocket:

#733 #706 layout api reference
  website/src/constants/menus/layoutMenus.js
  website/src/global.css
  website/src/modules/path/Path.js
  website/src/pages/layout/api-reference/collapse-btn.mdx
  website/src/pages/layout/api-reference/drawer-sidebar.mdx
  website/src/pages/layout/api-reference/edge-sidebar-builder.mdx
  website/src/pages/layout/api-reference/footer.mdx
  website/src/pages/layout/api-reference/fullscreen.mdx
  website/src/pages/layout/api-reference/header-builder.mdx
  website/src/pages/layout/api-reference/header.mdx
  website/src/pages/layout/api-reference/inset-avoiding-view.mdx
  website/src/pages/layout/api-reference/inset-container.mdx
  website/src/pages/layout/api-reference/inset-footer.mdx
  website/src/pages/layout/api-reference/inset-sidebar-builder.mdx
  website/src/pages/layout/api-reference/inset-sidebar.mdx
  website/src/pages/layout/api-reference/layout-builder.mdx
  website/src/pages/layout/api-reference/root.mdx
  website/src/pages/layout/api-reference/sidebar-trigger.mdx
  website/src/pages/layout/api-reference/swipeable-sidebar.mdx
Labels: PR: Docs :memo:

#736 #721 no styles in firefox
  website/src/components/layout/IFrame.js
  website/src/templates/documentation.css
Labels: PR: Bug Fix :bug:

#707 #541 border select
  package.json
  packages/mui-styles/src/select/border/borderSelect.styles.js
  packages/mui-styles/src/select/border/index.js
  website/package.json
  website/src/constants/creators.js
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/select/border/BorderSelect.js
  website/src/docs/styles/select/border/index.js
  website/src/docs/styles/select/border/index.md
  website/src/docs/styles/select/index.js
  website/src/fontawesome.js
  website/src/pages/styles/select.js
  yarn.lock
Labels: PR: New Feature :rocket:

#743 #718 Layout v4 features documentation
  website/src/constants/menus/layoutMenus.js
  website/src/pages/layout/features/auto-collapse.mdx
  website/src/pages/layout/features/header-magnet.mdx
  website/src/pages/layout/features/persistent-behavior.mdx
  website/src/templates/DocTemplate.js
  yarn.lock
Labels: PR: Docs :memo:

#761 feat: 🎸 make EdgeSidebar expandable on collapsed state
  .firebase/hosting.d2Vic2l0ZS9wdWJsaWM.cache
  packages/mui-layout/src/components/DrawerSidebar/DrawerSidebar.tsx
  packages/mui-layout/src/components/SwipeableSidebar/SwipeableSidebar.tsx
  packages/mui-layout/src/contexts/SidebarContext.tsx
  packages/mui-layout/src/hooks/index.ts
  packages/mui-layout/src/hooks/useSidebar.ts
  website/src/App.js
Labels: PR: New Feature :rocket:

#762 #705 custom trigger
  packages/mui-layout/src/components/CollapseBtn/CollapseBtn.tsx
  packages/mui-layout/src/components/SidebarTrigger/SidebarTrigger.tsx
  packages/mui-layout/src/hooks/index.ts
  packages/mui-layout/src/hooks/useSidebarCollapse.ts
  packages/mui-layout/src/hooks/useSidebarCta.ts
  packages/mui-layout/src/hooks/useSidebarTrigger.ts
  packages/mui-layout/src/index.ts
  website/src/components/atoms/CarbonAds.css
  website/src/components/atoms/CarbonAds.js
  website/src/components/atoms/CodeSandbox.js
  website/src/constants/menus/layoutMenus.js
  website/src/pages/layout/advanced/custom-trigger.mdx
  website/src/templates/DocTemplate.js
Labels: PR: Docs :memo:

#760 Documentation Spelling Correction
  website/src/pages/layout/core-concept.mdx
Labels: PR: Docs :memo:

#770 docs: ✏️ add layout starters page
  website/src/components/molecules/BrandCard.js
  website/src/constants/menus/layoutMenus.js
  website/src/pages/layout/starters.mdx
  website/src/templates/DocTemplate.js
Labels: PR: Docs :memo:

#773 docs: ✏️ update NextJS to layout starters
  package.json
  website/src/pages/layout/starters.mdx
Labels: PR: Docs :memo:

#776 #539 outline select 1
  packages/mui-styles/src/select/outline/index.js
  packages/mui-styles/src/select/outline/outlineSelect.styles.js
  website/src/docs/styles/select/outline/OutlineSelect.js
  website/src/docs/styles/select/outline/index.js
  website/src/docs/styles/select/outline/index.md
Labels: PR: New Feature :rocket:

#799 feat: 🎸 add row gutter styles in util
  packages/mui-styles/src/gutter/row/index.ts
  packages/mui-styles/src/gutter/row/rowGutter.styles.ts
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/gutter/index.js
  website/src/docs/styles/gutter/row/RowGutterStyle.js
  website/src/docs/styles/gutter/row/index.js
  website/src/docs/styles/gutter/row/index.md
  website/src/pages/styles/gutter.js
Labels: PR: New Feature :rocket:

#800 feat: 🎸 add sized icon button style
  packages/mui-styles/src/iconButton/sized/index.ts
  packages/mui-styles/src/iconButton/sized/sizedIconButton.styles.ts
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/iconButton/index.js
  website/src/docs/styles/iconButton/sized/SizedIconButtonStyle.js
  website/src/docs/styles/iconButton/sized/index.js
  website/src/docs/styles/iconButton/sized/index.md
  website/src/pages/styles/icon-button.js
Labels: PR: New Feature :rocket:

#803 feat: 🎸 add Gmail button component
  packages/mui-components/src/button/gmail/GmailButton.js
  packages/mui-components/src/button/gmail/GmailButton.stories.js
  packages/mui-components/src/button/gmail/GmailButton.test.js
  packages/mui-components/src/button/gmail/index.js
  website/src/constants/menus/componentMenus.js
  website/src/docs/components/button/gmail/GmailButtonDemo.js
  website/src/docs/components/button/gmail/index.js
  website/src/docs/components/button/gmail/index.md
  website/src/docs/components/button/index.js
  website/src/pages/components/button.js
  website/src/pages/components/button/gmail/index.js
Labels: PR: New Feature :rocket:

#806 feat: 🎸 add avatar button & google avatar style
  packages/mui-styles/src/avatar/google/googleAvatar.styles.ts
  packages/mui-styles/src/avatar/google/index.ts
  packages/mui-styles/src/iconButton/sized/sizedIconButton.styles.ts
  website/src/constants/menus/styleMenus.js
  website/src/docs/styles/avatar/google/GoogleAvatarStyle.js
  website/src/docs/styles/avatar/google/index.js
  website/src/docs/styles/avatar/google/index.md
  website/src/docs/styles/avatar/index.js
  website/src/docs/styles/button/avatar/AvatarButtonStyle.js
  website/src/docs/styles/button/avatar/index.js
  website/src/docs/styles/button/avatar/index.md
  website/src/docs/styles/iconButton/sized/SizedIconButtonStyle.js
  website/src/pages/styles/avatar.js
  website/src/utils/docGen.js
Labels: PR: New Feature :rocket:

#808 feat: 🎸 add GmailTabs style
  packages/mui-styles/src/tabs/gmail/gmailTabs.styles.ts
  packages/mui-styles/src/tabs/gmail/index.ts
  packages/mui-styles/src/tabs/index.ts
  website/src/components/organisms/CustomComponentGrid.js
  website/src/docs/styles/tabs/gmail/GmailTabsStyle.js
  website/src/docs/styles/tabs/gmail/index.js
  website/src/docs/styles/tabs/gmail/index.md
Labels: PR: New Feature :rocket:

#810 feat: 🎸 add delay expand action
  packages/mui-layout/src/contexts/SidebarContext.tsx
  packages/mui-layout/src/utils/constant.ts
Labels: PR: Performance :zap:

#812 feat: 🎸 add gmail list item style
  packages/mui-styles/src/listItem/gmail/gmailListItem.styles.ts
  packages/mui-styles/src/listItem/gmail/index.ts
  website/src/docs/styles/listItem/gmail/GmailListItemStyle.js
  website/src/docs/styles/listItem/gmail/index.js
  website/src/docs/styles/listItem/gmail/index.md
Labels: PR: New Feature :rocket:

#814 feat: 🎸 add gmail collapsible menu style
  packages/mui-components/src/sidebarItem/gmail/GmailSidebarItem.tsx
  packages/mui-components/src/sidebarItem/gmail/gmailSidebarItem.styles.ts
  website/src/docs/styles/collapsibleMenu/gmail/GmailCollapsibleMenuStyle.js
  website/src/docs/styles/collapsibleMenu/gmail/index.js
  website/src/docs/styles/collapsibleMenu/gmail/index.md
Labels: PR: New Feature :rocket:

#816 feat: 🎸 add ArrowMenu component
  packages/mui-components/src/menu/arrow/ArrowMenu.stories.js
  packages/mui-components/src/menu/arrow/ArrowMenu.test.js
  packages/mui-components/src/menu/arrow/ArrowMenu.tsx
  packages/mui-components/src/menu/arrow/index.ts
  website/src/docs/components/menu/arrow/ArrowMenuDemo.js
  website/src/docs/components/menu/arrow/index.js
  website/src/docs/components/menu/arrow/index.md
  website/src/pages/components/menu/arrow/index.js
Labels: PR: New Feature :rocket:

#827 feat: 🎸 add Gmail clone to layout
  packages/mui-mockup/src/brands/gmail/AppContent.js
  packages/mui-mockup/src/brands/gmail/AppFooter.js
  packages/mui-mockup/src/brands/gmail/AppHeader.js
  packages/mui-mockup/src/brands/gmail/AppSidebar.js
  packages/mui-mockup/src/brands/gmail/AppSubsidebar.js
  packages/mui-mockup/src/brands/gmail/CustomTrigger.js
  packages/mui-mockup/src/brands/gmail/MailListItem.js
  packages/mui-mockup/src/brands/gmail/index.js
  website/src/constants/menus/layoutMenus.js
  website/src/docs/layout/clones/gmail/GmailDemo.js
  website/src/docs/layout/clones/gmail/index.js
  website/src/docs/layout/clones/gmail/index.md
  website/src/pages/layout/clones/gmail.js
Labels: PR: style :lipstick:
