Repository siriwatknp/mui-treasury, pull requests merged in 2020-01, with the labels that each got.

#371 #369 cart layout clone
  .eslintrc
  packages/mui-layout/src/__tests__/models/insetSidebar.test.js
  packages/mui-layout/src/components/internal/SharedInsetSidebar.js
  packages/mui-layout/src/models/insetSidebar.js
  packages/mui-layout/src/utils/ConfigGenerator/SidebarGenerator.js
  packages/mui-mockup/src/brands/dailyShopping/DailyCart.js
  packages/mui-mockup/src/brands/dailyShopping/DailyCheckout.js
  packages/mui-mockup/src/brands/dailyShopping/DailyHeader.js
  packages/mui-mockup/src/brands/dailyShopping/DailyInteger.js
  packages/mui-mockup/src/brands/dailyShopping/DailyLogo.js
  packages/mui-mockup/src/brands/dailyShopping/DailySearch.js
  packages/mui-mockup/src/brands/dailyShopping/DailySizeSelector.js
  packages/mui-mockup/src/brands/dailyShopping/DailySummary.js
  packages/mui-mockup/src/brands/dailyShopping/dailyShoppingTheme.js
  packages/mui-mockup/src/brands/dailyShopping/index.js
  website/src/constants/menus.js
  website/src/docs/layout/clones/shoppingCart/ShoppingCartDemo.js
  website/src/docs/layout/clones/shoppingCart/index.js
  website/src/docs/layout/clones/shoppingCart/index.md
  website/src/pages/layout/clones/shopping-cart.js
Labels: PR: style :lipstick:

#375 Fix layout persistent behavior when anchor="right"
  packages/mui-layout/src/__tests__/models/container.test.js
  packages/mui-layout/src/__tests__/models/content.test.js
  packages/mui-layout/src/__tests__/models/edgeEffect.test.js
  packages/mui-layout/src/__tests__/models/footer.test.js
  packages/mui-layout/src/__tests__/models/header.test.js
  packages/mui-layout/src/__tests__/utils.test.js
  packages/mui-layout/src/models/container.js
  packages/mui-layout/src/models/content.js
  packages/mui-layout/src/models/edgeEffect.js
  packages/mui-layout/src/models/footer.js
  packages/mui-layout/src/models/header.js
  packages/mui-layout/src/models/width.js
  packages/mui-layout/src/utils/combineMargin.js
  packages/mui-layout/src/utils/toValidCssValue.js
  website/src/pages/layout/develop.js
Labels: PR: Bug Fix :bug:

#376 fix: 🐛 Shopping clone ios bugs
  website/src/docs/layout/clones/shoppingCart/ShoppingCartDemo.js
Labels: PR: Bug Fix :bug:

#394 [layout] added sidebar check into useInsetBreakpoint hook
  packages/mui-layout/src/hooks/useInsetBreakpoint.js
Labels: PR: Bug Fix :bug:

#399 Layout Tutorial Page
  packages/mui-layout/src/styles/header.styles.js
  website/gatsby-browser.js
  website/gatsby-config.js
  website/gatsby-node.js
  website/src/App.js
  website/src/components/organisms/SloganSection.js
  website/src/constants/menus.js
  website/src/global.css
  website/src/pages/layout/tutorials/dashboard-layout.md
  website/src/templates/DocTemplate.js
  website/src/utils/typography.js
Labels: PR: Docs :memo:

#402 fix: 🐛 empty config error and add more tests to cover
  packages/mui-layout/src/__tests__/content.test.js
  packages/mui-layout/src/__tests__/footer.test.js
  packages/mui-layout/src/__tests__/header.test.js
  packages/mui-layout/src/__tests__/secondarySidebar.test.js
  packages/mui-layout/src/__tests__/sidebar.test.js
  packages/mui-layout/src/components/Footer.js
  packages/mui-layout/src/components/Header.js
  packages/mui-layout/src/components/HeaderOffset.js
  packages/mui-layout/src/components/internal/SharedSidebar.js
Labels: PR: Bug Fix :bug:

#403 docs: ✏️ add blog layout tutorial
  website/src/components/organisms/ModuleProjector.js
  website/src/constants/menus.js
  website/src/global.css
  website/src/modules/path/Path.js
  website/src/pages/layout/tutorials/blog-layout.md
  website/src/pages/layout/tutorials/dashboard-layout.md
Labels: PR: Docs :memo:

#423 fix: 🐛 add gatsby-plugin-catch-links for markdown
  website/gatsby-config.js
  website/package.json
  website/src/modules/path/Path.js
  yarn.lock
Labels: PR: Bug Fix :bug:

#429 feat: 🎸 add responsive view to components
  packages/mui-styles/src/tabs/inside-triangle/insideTriangleTabs.styles.js
  website/src/components/layout/BrowserIFrame.js
  website/src/components/layout/PageFooter.js
  website/src/components/molecules/ShowcaseWidget.js
  website/src/components/organisms/DefaultSection.js
  website/src/containers/Demo/DemoSourceDrawer.js
  website/src/docs/components/card/blog/BlogCard.js
  website/src/docs/components/card/engagement/EngagementCard.js
  website/src/docs/components/card/news/NewsCard.js
  website/src/docs/components/card/project/ProjectCard.js
  website/src/docs/components/carousel/parallax/ParallaxCarousel.js
Labels: PR: New Feature :rocket:
